version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: inventory_sendosai
      POSTGRES_USER: sendosai
      POSTGRES_PASSWORD: 123456
    networks:
      - django_network

  web:
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "inventory_sendosai.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://sendosai:123456@db:5432/inventory_sendosai
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
